### ISSUE TITLE
 Complete Work

### ISSUE THREAD

**Issue by moyosolaa** [hunt-max/Predict_house_price#1]
Hi, I followed your tutorial to this github link. I've been trying to find resources about deploying ml models to flutter. Your code was a great eye opener but I noticed both the tutorial and code are not complete, maybe it's intentional I don't know, please is it possible I get the full work. I'll really appreciate this.
You can send me a mail at adekanmbi.yosola@gmail.com or I'll just come back to read your reply here. Thank you.

**Comment by hunt-max** [comment]
Hi, 
Thanks for bringing this to my notice. I have edited the article to include the relevant content along with links to the complete code. You can find it [here](https://medium.com/@gautammenghani201/expose-ml-models-as-rest-api-using-flask-and-access-via-flutter-ff6db093a1bf).
